name: Angular CI

on:
  push:

jobs:
         
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./INF354_Assignment2/Assignment2_u21598267
        run: npm install
      - name: Start the application
        working-directory: ./INF354_Assignment2/Assignment2_u21598267
        run: (npm start && exit 0) || (./rollback.sh && exit 1)


