name: Angular CI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./INF354_Assignment2/Assignment2_u21598267
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./WebApp
        run: npm install
      - name: Start the application
        working-directory: ./WebApp
        run: npm start || ./rollback.sh


