name: Angular CI

on:
  push:
    branches:
      - main  # Only trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./INF354_Assignment2/Assignment2_u21598267
        run: |
          npm install || true  # Ignore npm install failure
          chmod +x ./rollback.sh  # Ensure execute permissions
          ./rollback.sh  # Run the rollback script
      - name: Start the application
        working-directory: ./INF354_Assignment2/Assignment2_u21598267
        run: |
          (npm start --prod --project Assignment2_u21598267 & sleep 5; kill $!) || (./rollback.sh && exit 1)




